//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InferenceStack) DeepCopyInto(out *InferenceStack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InferenceStack) DeepCopy() *InferenceStack {
	if in == nil {
		return nil
	}
	out := new(InferenceStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *InferenceStack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InferenceStackList) DeepCopyInto(out *InferenceStackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InferenceStackList) DeepCopy() *InferenceStackList {
	if in == nil {
		return nil
	}
	out := new(InferenceStackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *InferenceStackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InferenceStackSpec) DeepCopyInto(out *InferenceStackSpec) {
	*out = *in
	in.Pool.DeepCopyInto(&out.Pool)
	if in.EPP.Weights != nil {
		in, out := &in.EPP.Weights, &out.EPP.Weights
		*out = new(EPPWeights)
		**out = **in
	} else {
		out.EPP = in.EPP
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPRoute != nil {
		in, out := &in.HTTPRoute, &out.HTTPRoute
		*out = new(HTTPRouteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DCGM != nil {
		in, out := &in.DCGM, &out.DCGM
		*out = new(DCGMSpec)
		**out = **in
	}
	if in.DistributedCloud != nil {
		in, out := &in.DistributedCloud, &out.DistributedCloud
		*out = new(DistributedCloudConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InferenceStackSpec) DeepCopy() *InferenceStackSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InferencePoolSpec) DeepCopyInto(out *InferencePoolSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InferencePoolSpec) DeepCopy() *InferencePoolSpec {
	if in == nil {
		return nil
	}
	out := new(InferencePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *EPPSpec) DeepCopyInto(out *EPPSpec) {
	*out = *in
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = new(EPPWeights)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *EPPSpec) DeepCopy() *EPPSpec {
	if in == nil {
		return nil
	}
	out := new(EPPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]ThresholdSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HTTPRouteSpec) DeepCopyInto(out *HTTPRouteSpec) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HTTPRouteSpec) DeepCopy() *HTTPRouteSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *InferenceStackStatus) DeepCopyInto(out *InferenceStackStatus) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ChildStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciledAt != nil {
		in, out := &in.LastReconciledAt, &out.LastReconciledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *InferenceStackStatus) DeepCopy() *InferenceStackStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceStackStatus)
	in.DeepCopyInto(out)
	return out
}

// --- GatewayBundle deep copy ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayBundle) DeepCopyInto(out *GatewayBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayBundle) DeepCopy() *GatewayBundle {
	if in == nil {
		return nil
	}
	out := new(GatewayBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GatewayBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayBundleList) DeepCopyInto(out *GatewayBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayBundleList) DeepCopy() *GatewayBundleList {
	if in == nil {
		return nil
	}
	out := new(GatewayBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GatewayBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayBundleSpec) DeepCopyInto(out *GatewayBundleSpec) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]GatewayListenerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NginxProxy != nil {
		in, out := &in.NginxProxy, &out.NginxProxy
		*out = new(NginxProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WAF != nil {
		in, out := &in.WAF, &out.WAF
		*out = new(WAFSpec)
		**out = **in
	}
	if in.SnippetsFilter != nil {
		in, out := &in.SnippetsFilter, &out.SnippetsFilter
		*out = new(SnippetsFilterSpec)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(GatewayTLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayBundleSpec) DeepCopy() *GatewayBundleSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayBundleStatus) DeepCopyInto(out *GatewayBundleStatus) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ChildStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciledAt != nil {
		in, out := &in.LastReconciledAt, &out.LastReconciledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayBundleStatus) DeepCopy() *GatewayBundleStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayListenerSpec) DeepCopyInto(out *GatewayListenerSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ListenerTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedRoutes != nil {
		in, out := &in.AllowedRoutes, &out.AllowedRoutes
		*out = new(AllowedRoutesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayListenerSpec) DeepCopy() *GatewayListenerSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ListenerTLSSpec) DeepCopyInto(out *ListenerTLSSpec) {
	*out = *in
	if in.CertificateRefs != nil {
		in, out := &in.CertificateRefs, &out.CertificateRefs
		*out = make([]CertRefSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ListenerTLSSpec) DeepCopy() *ListenerTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AllowedRoutesSpec) DeepCopyInto(out *AllowedRoutesSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(RouteNamespacesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AllowedRoutesSpec) DeepCopy() *AllowedRoutesSpec {
	if in == nil {
		return nil
	}
	out := new(AllowedRoutesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *RouteNamespacesSpec) DeepCopyInto(out *RouteNamespacesSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *RouteNamespacesSpec) DeepCopy() *RouteNamespacesSpec {
	if in == nil {
		return nil
	}
	out := new(RouteNamespacesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NginxProxySpec) DeepCopyInto(out *NginxProxySpec) {
	*out = *in
	if in.RewriteClientIP != nil {
		in, out := &in.RewriteClientIP, &out.RewriteClientIP
		*out = new(RewriteClientIPSpec)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(NginxTelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NginxProxySpec) DeepCopy() *NginxProxySpec {
	if in == nil {
		return nil
	}
	out := new(NginxProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NginxTelemetrySpec) DeepCopyInto(out *NginxTelemetrySpec) {
	*out = *in
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(OTelExporterSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NginxTelemetrySpec) DeepCopy() *NginxTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(NginxTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GatewayTLSSpec) DeepCopyInto(out *GatewayTLSSpec) {
	*out = *in
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make([]TLSSecretRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GatewayTLSSpec) DeepCopy() *GatewayTLSSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// --- DistributedCloudPublish deep copy ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DistributedCloudPublish) DeepCopyInto(out *DistributedCloudPublish) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DistributedCloudPublish) DeepCopy() *DistributedCloudPublish {
	if in == nil {
		return nil
	}
	out := new(DistributedCloudPublish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *DistributedCloudPublish) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DistributedCloudPublishList) DeepCopyInto(out *DistributedCloudPublishList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedCloudPublish, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DistributedCloudPublishList) DeepCopy() *DistributedCloudPublishList {
	if in == nil {
		return nil
	}
	out := new(DistributedCloudPublishList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *DistributedCloudPublishList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DistributedCloudPublishSpec) DeepCopyInto(out *DistributedCloudPublishSpec) {
	*out = *in
	in.DistributedCloud.DeepCopyInto(&out.DistributedCloud)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DistributedCloudPublishSpec) DeepCopy() *DistributedCloudPublishSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedCloudPublishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DistributedCloudPublishStatus) DeepCopyInto(out *DistributedCloudPublishStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DistributedCloudPublishStatus) DeepCopy() *DistributedCloudPublishStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedCloudPublishStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DistributedCloudConfig) DeepCopyInto(out *DistributedCloudConfig) {
	*out = *in
	if in.MultiRegion.Regions != nil {
		in, out := &in.MultiRegion.Regions, &out.MultiRegion.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DistributedCloudConfig) DeepCopy() *DistributedCloudConfig {
	if in == nil {
		return nil
	}
	out := new(DistributedCloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ChildStatus) DeepCopyInto(out *ChildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ChildStatus) DeepCopy() *ChildStatus {
	if in == nil {
		return nil
	}
	out := new(ChildStatus)
	*out = *in
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ThresholdSpec) DeepCopyInto(out *ThresholdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ThresholdSpec) DeepCopy() *ThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdSpec)
	*out = *in
	return out
}
